version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
  web:
    env_file:
      .env
    build:
      context: .
      dockerfile: /home/admin1/PycharmProjects/fundoo/Dockerfile
    command: python fundoo/manage.py runserver 8000
    ports:
      - "8000:8000"
    depends_on:
      - db