version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE : noothan
      MYSQL_USER : noothan
      MYSQL_PASSWORD : noothan
      MYSQL_ROOT_PASSWORD : noothan
  web:
    env_file:
      .env
    build:
      context: .
      dockerfile: /home/admin1/PycharmProjects/fundoo/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db