# Generated by Django 2.2.6 on 2019-12-07 13:22

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191130_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#00FF00', '#0000FF'], null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
