# Generated by Django 2.2.6 on 2019-12-17 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20191207_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='pin',
            new_name='is_pin',
        ),
        migrations.RemoveField(
            model_name='note',
            name='collab',
        ),
        migrations.AddField(
            model_name='note',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
